export const grayScaleBg =[
    {
        text:"text-dark",
        background:"bg-gray-100",
        content:"bg-gray-100"
    },
    {
        text:"text-dark",
        background:"bg-gray-200",
        content:"bg-gray-200"
    },
    {
        text:"text-dark",
        background:"bg-gray-300",
        content:"bg-gray-300"
    },
    {
        text:"text-dark",
        background:"bg-gray-400",
        content:"bg-gray-400"
    },
    {
        text:"text-light",
        background:"bg-gray-500",
        content:"bg-gray-500"
    },
    {
        text:"text-light",
        background:"bg-gray-600",
        content:"bg-gray-600"
    },
    {
        text:"text-light",
        background:"bg-gray-700",
        content:"bg-gray-700"
    },
    {
        text:"text-light",
        background:"bg-gray-800",
        content:"bg-gray-800"
    },
    {
        text:"text-light",
        background:"bg-gray-900",
        content:"bg-gray-900"
    }
]