export const textColors =[
    {
        background:"bg-dark",
        text:"text-gray-100"
    },
    {
        background:"bg-dark",
        text:"text-gray-200"
    },
    {
        background:"bg-dark",
        text:"text-gray-300"
    },
    {
        background:"bg-dark",
        text:"text-gray-400"
    },
    {
        background:"bg-light",
        text:"text-gray-500"
    },
    {
        background:"bg-light",
        text:"text-gray-600"
    },
    {
        background:"bg-light",
        text:"text-gray-700"
    },
    {
        background:"bg-light",
        text:"text-gray-800"
    },
    {
        background:"bg-light",
        text:"text-gray-900"
    }
]